[tool.poetry]
name = "coursework"
version = "0.1.0"
description = ""
authors = ["sofia <example@mail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
